apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: thingworx-secrets
  namespace: external-secrets-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-store
  target:
    name: thingworx-secrets
    creationPolicy: Owner
  data:
    - secretKey: AKS-NS
      remoteRef:
        key: AKS-NS
    - secretKey: ACR-TWX-SERVER
      remoteRef:
        key: ACR-TWX-SERVER
    - secretKey: ACR-TWX-USER
      remoteRef:
        key: ACR-TWX-USER
    - secretKey: AKS-PERS-LOCATION
      remoteRef:
        key: AKS-PERS-LOCATION
    - secretKey: AKS-PERS-RESOURCE-GROUP
      remoteRef:
        key: AKS-PERS-RESOURCE-GROUP
    - secretKey: AKS-PERS-SHARE-NAME
      remoteRef:
        key: AKS-PERS-SHARE-NAME
    - secretKey: AKS-PERS-SHARE-NAME-SKUNAME
      remoteRef:
        key: AKS-PERS-SHARE-NAME-SKUNAME
    - secretKey: AKS-PERS-STORAGE-ACCOUNT-NAME
      remoteRef:
        key: AKS-PERS-STORAGE-ACCOUNT-NAME
    - secretKey: AKS-FR-RESOURCE-GROUP
      remoteRef:
        key: AKS-FR-RESOURCE-GROUP
    - secretKey: AKS-FR-STORAGE-ACCOUNT-NAME
      remoteRef:
        key: AKS-FR-STORAGE-ACCOUNT-NAME
    - secretKey: AKS-FR-STORAGE-SHARENAME
      remoteRef:
        key: AKS-FR-STORAGE-SHARENAME
    - secretKey: AKS-FR-SHARE-NAME-SKUNAME
      remoteRef:
        key: AKS-FR-SHARE-NAME-SKUNAME
    - secretKey: AKS-MONITORING-STORAGE-ACCOUNT-NAME
      remoteRef:
        key: AKS-MONITORING-STORAGE-ACCOUNT-NAME
    - secretKey: AKS-MONITORING-RESOURCE-GROUP
      remoteRef:
        key: AKS-MONITORING-RESOURCE-GROUP
    - secretKey: AKS-TWX-INGRESS-CERT
      remoteRef:
        key: AKS-TWX-INGRESS-CERT
    - secretKey: INGRESS-IP
      remoteRef:
        key: INGRESS-IP
    - secretKey: TWX-LS-KEY
      remoteRef:
        key: TWX-LS-KEY
    - secretKey: SSL-KEYSTORE-PASSWORD
      remoteRef:
        key: SSL-KEYSTORE-PASSWORD
    - secretKey: KEYSTORE-PASSWORD
      remoteRef:
        key: KEYSTORE-PASSWORD
    - secretKey: THINGWORX-INITIAL-ADMIN-PASSWORD
      remoteRef:
        key: THINGWORX-INITIAL-ADMIN-PASSWORD
    - secretKey: TOMCAT-CLIENT-PASSWORD
      remoteRef:
        key: TOMCAT-CLIENT-PASSWORD
    - secretKey: TOMCAT-TRUSTSTORE-PASSWORD
      remoteRef:
        key: TOMCAT-TRUSTSTORE-PASSWORD
    - secretKey: TWX-EMS-URL
      remoteRef:
        key: TWX-EMS-URL
    - secretKey: TWX-ENABLE-CONSOLE-OUTPUT
      remoteRef:
        key: TWX-ENABLE-CONSOLE-OUTPUT
    - secretKey: TWX-ENABLE-CLUSTERED-MODE
      remoteRef:
        key: TWX-ENABLE-CLUSTERED-MODE
    - secretKey: TWX-SECRET-PROVISIONING-APP-KEY
      remoteRef:
        key: TWX-SECRET-PROVISIONING-APP-KEY
    - secretKey: TWX-PLATFORM-ID
      remoteRef:
        key: TWX-PLATFORM-ID
    - secretKey: TWX-POOL-NAME
      remoteRef:
        key: TWX-POOL-NAME
    - secretKey: TWX-REPLICA-COUNT
      remoteRef:
        key: TWX-REPLICA-COUNT
    - secretKey: TWX-CPU-REQUEST
      remoteRef:
        key: TWX-CPU-REQUEST
    - secretKey: TWX-CPU-LIMIT
      remoteRef:
        key: TWX-CPU-LIMIT
    - secretKey: TWX-MEMORY-REQUEST
      remoteRef:
        key: TWX-MEMORY-REQUEST
    - secretKey: TWX-MEMORY-LIMIT
      remoteRef:
        key: TWX-MEMORY-LIMIT
    - secretKey: TWX-CATALINA-OPTS
      remoteRef:
        key: TWX-CATALINA-OPTS
    - secretKey: EMG-REPLICA-COUNT
      remoteRef:
        key: EMG-REPLICA-COUNT
    - secretKey: EMESSAGE-POOL-NAME
      remoteRef:
        key: EMESSAGE-POOL-NAME
    - secretKey: EMG-CPU-REQUEST
      remoteRef:
        key: EMG-CPU-REQUEST
    - secretKey: EMG-CPU-LIMIT
      remoteRef:
        key: EMG-CPU-LIMIT
    - secretKey: EMG-MEMORY-REQUEST
      remoteRef:
        key: EMG-MEMORY-REQUEST
    - secretKey: EMG-MEMORY-LIMIT
      remoteRef:
        key: EMG-MEMORY-LIMIT
    - secretKey: EMG-CATALINA-OPTS
      remoteRef:
        key: EMG-CATALINA-OPTS
    - secretKey: TWX-DATA-DATABASE-USERNAME
      remoteRef:
        key: TWX-DATA-DATABASE-USERNAME
    - secretKey: TWX-DATA-DATABASE-PASSWORD
      remoteRef:
        key: TWX-DATA-DATABASE-PASSWORD
    - secretKey: TWX-DATABASE-USERNAME
      remoteRef:
        key: TWX-DATABASE-USERNAME
    - secretKey: TWX-DATABASE-PASSWORD
      remoteRef:
        key: TWX-DATABASE-PASSWORD
    - secretKey: DATABASE-HOST
      remoteRef:
        key: DATABASE-HOST
    - secretKey: DATABASE-PORT
      remoteRef:
        key: DATABASE-PORT
    - secretKey: DATABASE-ADMIN-USERNAME
      remoteRef:
        key: DATABASE-ADMIN-USERNAME
    - secretKey: DATABASE-ADMIN-PASSWORD
      remoteRef:
        key: DATABASE-ADMIN-PASSWORD
