loki:
  image:
    registry: docker.io
    repository: grafana/loki
    tag: 3.5.3
lokiCanary:
  image:
    registry: docker.io
    repository: grafana/loki-canary
    tag: null
gateway:
  image:
    registry: docker.io
    repository: nginxinc/nginx-unprivileged
    tag: 1.29-alpine
memcached:
  image:
    repository: memcached
    tag: 1.6.38-alpine
    pullPolicy: IfNotPresent
memcachedExporter:
  enabled: true
  image:
    repository: prom/memcached-exporter
    tag: v0.15.3
    pullPolicy: IfNotPresent
sidecar:
  image:
    repository: kiwigrid/k8s-sidecar
    tag: 1.30.7
