# MongoDB Deployment for Diffy Application (AKS - No PVC)
# This includes all necessary Kubernetes resources
# --spring.data.mongodb.uri=mongodb://localhost:27017/diffy
# java -jar diffy.jar   --candidate=localhost:3000   --master.primary=localhost:3000   --master.secondary=localhost:3000   --service.protocol=http   --serviceName=sample-app   --proxy.port=8880   --admin.port=8881   --summary.email=your-email@example.com   --spring.data.mongodb.uri=mongodb://localhost:27017/diffy
---
# MongoDB Service
apiVersion: v1
kind: Service
metadata:
  name: diffy-mongo-service
  namespace: default
  labels:
    app: diffy-mongo
spec:
  selector:
    app: diffy-mongo
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
      protocol: TCP
  type: ClusterIP
---
# MongoDB Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diffy-mongo
  namespace: default
  labels:
    app: diffy-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diffy-mongo
  template:
    metadata:
      labels:
        app: diffy-mongo
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0.6
        ports:
        - containerPort: 27017
          name: mongodb
        env:
        - name: MONGO_INITDB_DATABASE
          value: "diffy"
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: mongodb-data
        emptyDir: {}
---
# Optional: ConfigMap for MongoDB configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: default
data:
  mongod.conf: |
    storage:
      dbPath: /data/db
    net:
      port: 27017
      bindIp: 0.0.0.0
    systemLog:
      destination: file
      path: /var/log/mongodb/mongod.log
      logAppend: true
    processManagement:
      fork: false
