{{- if .Values.tlsSecrets.enabled }}
{{- range .Values.namespaces }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $.Values.tlsSecrets.name }}
  namespace: {{ .name }}
  {{- with $.Values.tlsSecrets.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $.Values.tlsSecrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: {{ $.Values.tlsSecrets.refreshInterval }}
  secretStoreRef:
    kind: {{ $.Values.secretStore.kind }}
    name: {{ $.Values.secretStore.name }}
  target:
    name: {{ $.Values.tlsSecrets.targetSecretName }}
    creationPolicy: {{ $.Values.tlsSecrets.creationPolicy }}
    template:
      type: kubernetes.io/tls
      {{- with $.Values.tlsSecrets.template.metadata }}
      metadata:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      data:
        tls.crt: {{ printf "{{ .%s }}" $.Values.tlsSecrets.certSecretKey }}
        tls.key: {{ printf "{{ .%s }}" $.Values.tlsSecrets.keySecretKey }}
        {{- range $.Values.tlsSecrets.additionalData }}
        {{ .key }}: {{ printf "{{ .%s }}" .secretKey }}
        {{- end }}
  data:
    - secretKey: {{ $.Values.tlsSecrets.certSecretKey }}
      remoteRef:
        key: {{ $.Values.tlsSecrets.certRemoteKey }}
        {{- with $.Values.tlsSecrets.certRemoteProperty }}
        property: {{ . }}
        {{- end }}
    - secretKey: {{ $.Values.tlsSecrets.keySecretKey }}
      remoteRef:
        key: {{ $.Values.tlsSecrets.keyRemoteKey }}
        {{- with $.Values.tlsSecrets.keyRemoteProperty }}
        property: {{ . }}
        {{- end }}
    {{- range $.Values.tlsSecrets.additionalSecrets }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        {{- with .remoteRef.property }}
        property: {{ . }}
        {{- end }}
    {{- end }}
{{- end }}
{{- end }}
