name: Build with NAnt

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET Framework
      uses: microsoft/setup-msbuild@v1
    
    - name: Download and install NAnt 0.92
      run: |
        $url = "https://sourceforge.net/projects/nant/files/nant/0.92/nant-0.92-bin.zip/download"
        $output = "nant.zip"
        Invoke-WebRequest -Uri $url -OutFile $output -UseBasicParsing
        Expand-Archive -Path $output -DestinationPath "nant" -Force
        $nantPath = Join-Path $env:GITHUB_WORKSPACE "nant\nant-0.92\bin"
        echo $nantPath >> $env:GITHUB_PATH
  shell: powershell
