# pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: runner-work-pvc
  namespace: arc-runners
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: gp2  # Changed from "standard" to "gp2"
